In [1]:
import pandas as pd

# Woking with JSON

In [2]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [3]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-27,1777248001,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-27,1777248001,0.0389
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-27,1777248001,0.6730
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-27,1777248001,0.8660
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-27,1777248001,3.9500
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-27,1777248001,2.5300
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-27,1777248001,0.1760
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-27,1777248001,0.2000
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-27,1777248001,0.2670
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-27,1777248001,0.2670

# Working with SQL

In [4]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     -- ------------------------------------- 0.8/11.9 MB 1.7 MB/s eta 0:00:07
     ---- ----------------------------------- 1.3/11.9 MB 1.8 MB/s eta 0:00:06
     ------ --------------------------------- 1.8/11.9 MB 2.0 MB/s eta 0:00:06
     ------- -------------------------------- 2.4/11.9 MB 2.1 MB/s eta 0:00:05
     --------- ------------------------------ 2.9/11.9 MB 2.1 MB/s eta 0:00:05
     ------------ --------------------------- 3.7/11.9 MB 2.3 MB/s eta 0:00:04
     --------------- ------------------------ 4.7/11.9 MB 2.6 MB/s eta 0:00:03
     ------------------- -------------------- 5.8/11.9 MB 2.9 MB/s eta 0:00:03
     ----------------------- ---------------- 7.1/11.9 MB 3.2 MB/s eta 0:00:02
     ----------------------------- ---------- 8.7/11.9 MB 3.5 MB/s eta 0:00:01
     -------------------------------- ------- 9.7/11.9 MB 3.6 MB/s eta 0:00:01
     -------------------------------------- - 11.3/11.9 MB 3.8 MB/s eta 0:00:01
     ---------------------------------------  11.8/11.9 MB 3.9 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 3.7 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=248051 sha256=f241e75734aa0d0605c02e8f9f45fb46df85fe1354e1a3ce499f6c435550b57c
  Stored in directory: c:\users\nehul singh\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

[notice] A new release of pip is available: 25.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import mysql.connector

In [10]:
# conn = mysql.connector.connect(host='localhost',user='root',password='@nehul114911#',database='college')
conn = mysql.connector.connect(host='DESKTOP-C10U3SH',user='root',password='@nehul114911#',database='college')

InterfaceError: 2003: Can't connect to MySQL server on 'DESKTOP-C10U3SH:3306' (11001 getaddrinfo failed)

In [27]:
df = pd.read_sql_query("SELECT * FROM countrylanguage",conn)

In [28]:
df

    CountryCode    Language IsOfficial  Percentage
0           ABW       Dutch          T         5.3
1           ABW     English          F         9.5
2           ABW  Papiamento          F        76.7
3           ABW     Spanish          F         7.4
4           AFG     Balochi          F         0.9
..          ...         ...        ...         ...
979         ZMB      Tongan          F        11.0
980         ZWE     English          T         2.2
981         ZWE     Ndebele          F        16.2
982         ZWE      Nyanja          F         2.2
983         ZWE       Shona          F        72.1

[984 rows x 4 columns]